#!/bin/bash
# Checks for this app. Generated by tools/publish.py in the shared repository —
# edit it there.
set -euo pipefail
cd "$(dirname "$0")"
mkdir -p build shots

APPKIT="-framework AppKit -framework ServiceManagement -framework AVFoundation"
SOURCES=$(ls app/Sources/*.swift | grep -v '/main.swift$' | grep -v 'AppDelegate.swift$')
MANIFEST="products/megadrive-buddies.json"
APP="build/MegaDrive Buddies.app"

echo "== build =="
./build.sh >/dev/null
PLIST_MIN=$(/usr/libexec/PlistBuddy -c "Print :LSMinimumSystemVersion" app/Info.plist)
ARCH=$(lipo -info "$APP/Contents/MacOS/MegaDrive Buddies" | sed 's/.*: //')
echo "  Info.plist $PLIST_MIN / $ARCH"
case "$ARCH" in *arm64*) ;; *) echo "  FAIL missing arm64 slice"; exit 1;; esac

echo
echo "== the cast =="
swiftc -O $APPKIT $SOURCES tools/casttest/main.swift -o build/casttest
BUDDY_PRODUCT="$MANIFEST" BUDDY_APP="$APP" ./build/casttest

echo
echo "== the game cast =="
swiftc -O $APPKIT $SOURCES tools/gamecasttest/main.swift -o build/gamecasttest
BUDDY_PRODUCT="$MANIFEST" BUDDY_APP="$APP" ./build/gamecasttest

echo
echo "== one sprite per frame =="
swiftc -O $APPKIT $SOURCES tools/framestest/main.swift -o build/framestest
BUDDY_PRODUCT="$MANIFEST" BUDDY_APP="$APP" ./build/framestest

echo
echo "== what they talk about =="
swiftc -O $APPKIT $SOURCES tools/gametalktest/main.swift -o build/gametalktest
BUDDY_PRODUCT="$MANIFEST" ./build/gametalktest

echo
echo "== wander logic =="
swiftc -O $APPKIT $SOURCES tools/wandertest/main.swift -o build/wandertest
BUDDY_PRODUCT="$MANIFEST" ./build/wandertest

echo
echo "== liveliness =="
swiftc -O $APPKIT $SOURCES tools/alivetest/main.swift -o build/alivetest
BUDDY_PRODUCT="$MANIFEST" ./build/alivetest

echo
echo "all sections completed"
