import Foundation

/// What they talk about: video games, up to 1997, and nothing after.
///
/// The cutoff is the point of it. These are 16-bit characters standing on a
/// desktop thirty years later, so they talk about the era they came from —
/// arcades, cartridges, the console war, the games that were new to them.
/// Nothing here knows what happened next.
///
/// The facts are facts. Each one is something that actually happened, kept
/// short enough for a speech bubble; where a story is famous but the details
/// are contested, it's phrased as the story it is rather than stated flat.
enum GameTalk {

    struct Joke {
        let setup: String
        let punchline: String
    }

    /// One line of an exchange. `who` names a character when only that
    /// character can say it; nil means anybody can.
    struct Line {
        let who: String?
        let text: String
        init(_ who: String?, _ text: String) { self.who = who; self.text = text }
    }

    // MARK: - Facts

    static let facts: [String] = [
        "Nintendo was founded in 1889. It made playing cards for most of a century before it made a game.",
        "Sega is short for Service Games. It started out supplying coin-op machines to army bases in Japan.",
        "Space Invaders sped up as you shot the aliens because the hardware drew fewer of them faster. The bug shipped as difficulty.",
        "The Konami Code was written by a man porting Gradius to the NES who found his own game too hard to test.",
        "Tetris was written in 1984 by Alexey Pajitnov at the Soviet Academy of Sciences. He saw no royalties for over a decade.",
        "Donkey Kong's hero was called Jumpman. He got the name Mario later, from a landlord.",
        "Pac-Man's ghosts don't all chase you. One follows, one cuts you off, one wanders — that's why the maze feels alive.",
        "Pac-Man was built around eating because Namco wanted a game for people who weren't there to shoot things.",
        "Street Fighter II's combos were an accident. A timing bug let moves chain, and Capcom decided to keep it.",
        "The Mega Drive launched in Japan in 1988. America got it a year later, under the name Genesis.",
        "Sonic was very nearly called Mr Needlemouse.",
        "Sega released Sonic 2 everywhere on one day and called it Sonic 2sday: the 24th of November, 1992.",
        "The spin dash didn't exist in the first Sonic. There was no way to charge a roll standing still.",
        "Doom went out as shareware in 1993 — the first episode free, the rest by post.",
        "Myst has outsold every other PC game of the nineties, and the nineties aren't over yet.",
        "The blood in Mortal Kombat led to a US Senate hearing, and the hearing led to the ESRB in 1994.",
        "The PlayStation started life as a CD add-on Sony was building for the Super Nintendo. Nintendo walked away in 1991.",
        "Sega launched the Saturn in America four months early, announced on stage at E3 1995. Most shops found out that day.",
        "Virtua Fighter, in 1993, was the first fighting game built out of polygons.",
        "Lara Croft was called Laura Cruz in the early drafts of Tomb Raider.",
        "Crash Bandicoot spent development under the working title Willy the Wombat.",
        "Pokémon Red and Green came out in Japan in 1996 — on a Game Boy that was already seven years old.",
        "Final Fantasy VII shipped on three CDs in 1997. The install was optional. The discs were not.",
        "GoldenEye 007 was made at Rare in 1997 by a team where almost nobody had shipped a game before.",
        "They say Atari buried its unsold E.T. cartridges in a New Mexico landfill in 1983. Nobody has dug them up to check.",
        "The story goes that the first Pong cabinet was reported broken, and the fault was a coin box too full to take another quarter.",
        "Metroid, in 1986, revealed Samus as a woman if you finished it quickly enough.",
        "Super Mario Bros. 2 in the West is a reskin of a game called Doki Doki Panic. The Japanese sequel was thought too hard.",
        "The Mega Drive ran on a Motorola 68000 — the same processor family as the first Macintosh.",
        "Blast processing was a marketing phrase. The 68000 in a Mega Drive ran at about 7.6 MHz.",
        "Sonic 3 came with a battery so it could save. Most Mega Drive cartridges had nowhere to put your progress.",
        "Akuma was hidden in Super Street Fighter II Turbo in 1994, behind conditions almost nobody met by accident.",
        "Earthworm Jim's animation was drawn by hand, frame by frame, by animators who had worked in cartoons.",
        "Comix Zone put you inside a comic book, punching through panels the artist was drawing around you.",
        "ToeJam & Earl built its levels at random every time, an idea it borrowed from Rogue.",
        "Michael Jackson's Moonwalker, in 1990, had you rescuing children by dancing at people until they fell over.",
        "Shinobi III gave a ninja a horse in one stage and a surfboard in another, and nobody thought to stop it.",
        "Sparkster of Rocket Knight Adventures is an opossum. Everybody says squirrel.",
        "Treasure — Gunstar Heroes, Dynamite Headdy — was founded in 1992 by staff who had walked out of Konami.",
        "Pulseman was made by Game Freak, three years before the same studio made Pokémon.",
        "The Game Boy launched in 1989 and came bundled in the West with Tetris. It was black and white and it outlived everything.",
        "Street Fighter II was pirated as arcade boards, not discs. Rainbow Edition was a hacked chip, not a patch.",
        "Sonic CD shipped with a different soundtrack in America than in Japan. Both are the real one, depending who you ask.",
        "Nintendo's Game Boy shipped with a link cable, and the killer app for it turned out to be trading.",
        "The Turtles arcade cabinet in 1989 took four players at once. The home versions could manage two.",
        "Konami censored Michelangelo's nunchaku in some countries and gave him a grappling hook instead.",
        "Arcades charged by the credit, so difficulty was a business model. Home ports had to learn to be fair.",
        "There's a Z80 inside a Mega Drive as well as the 68000. Its whole job is the sound.",
        "Sega of America renamed the Mega Drive the Genesis. Somebody else already had the name.",
        "The Mega Drive pad had three buttons. Street Fighter II arrived and suddenly it needed six.",
        "Sonic 2 was made in America, at Sega Technical Institute, by a team half Japanese and half not.",
        "Yuzo Koshiro wrote his own assembler to program the Mega Drive's sound chip. Then he scored Streets of Rage with it.",
        "Alex Kidd was Sega's mascot before Sonic. He solved boss fights with rock-paper-scissors.",
        "The 32X sat on top of the Mega Drive like a mushroom and lasted about a year.",
        "Virtua Racing put an extra chip inside the cartridge, because the console couldn't do the maths on its own.",
        "Sonic & Knuckles had a slot in the top so you could lock another cartridge into it.",
        "The Game Gear was a Master System you could carry, and it ate six batteries in an afternoon.",
        "Mortal Kombat hid its blood behind a code here. On the other machine they turned it into sweat.",
        "Aladdin on this machine was animated by Disney. The version on the other one was a completely different game.",
        "Vectorman rendered its sprites in 3D first, in 1995, to fake more colours than the hardware had.",
        "Streets of Rage 3 came out of Japan as Bare Knuckle III. The Western release rewrote the story and made it harder.",
        "Michael Jackson's songs were sequenced onto the FM chip for Moonwalker. Smooth Criminal, on a sound chip.",
        "Treasure's first game was Gunstar Heroes, made by people who had left Konami to stop making licensed tie-ins.",
        "ToeJam & Earl's sequel dropped the random levels for a side-scroller, and nobody has stopped arguing about it.",
    ]

    // MARK: - Jokes

    static let jokes: [Joke] = [
        .init(setup: "How many mascots does it take to change a lightbulb?",
              punchline: "Two. One to change it, one to insist their version is faster."),
        .init(setup: "Why did the arcade cabinet never save any money?",
              punchline: "Everything it did cost a quarter."),
        .init(setup: "What's a hedgehog's favourite kind of music?",
              punchline: "Anything with a good loop."),
        .init(setup: "Why can't you trust a boss in a side-scroller?",
              punchline: "There's always a second phase."),
        .init(setup: "What did the 68000 say to the sound chip?",
              punchline: "You handle the music. I'll handle the pressure."),
        .init(setup: "Why did the RPG hero turn down a free room at the inn?",
              punchline: "He'd already saved."),
        .init(setup: "How can you tell a game was made in 1993?",
              punchline: "The blood is behind a code."),
        .init(setup: "What did Tetris say to the gap?",
              punchline: "Don't move. I've got something that fits."),
        .init(setup: "Why did the ghost stop chasing Pac-Man?",
              punchline: "He'd been going round in circles for years and finally noticed."),
        .init(setup: "Why was the platform character so anxious?",
              punchline: "Everywhere he went, the floor was optional."),
        .init(setup: "What's the difference between an arcade and a casino?",
              punchline: "The casino tells you the odds."),
        .init(setup: "Why did the beat-'em-up character eat the roast chicken off the pavement?",
              punchline: "It was in a barrel. That makes it fine."),
        .init(setup: "Why don't fighting-game rivals ever finish a conversation?",
              punchline: "Someone always shouts round two."),
        .init(setup: "What did the sprite say to the palette?",
              punchline: "Don't you change on me."),
        .init(setup: "Why did the ninja bring a surfboard to work?",
              punchline: "Stage four."),
        .init(setup: "What do you call a cartridge you have to blow into?",
              punchline: "Working, eventually."),
        .init(setup: "Why did the shopkeeper in the RPG never leave his shop?",
              punchline: "He was worried about the economy — he'd seen how much people had in their pockets."),
        .init(setup: "How does a 16-bit character apologise?",
              punchline: "Three frames of looking at his shoes."),
        .init(setup: "Why did the racing game character refuse to talk about the ending?",
              punchline: "No spoilers. Literally, the car didn't come with one."),
        .init(setup: "What's the most honest thing in an arcade?",
              punchline: "The high score table. It remembers exactly how bad you were."),
        .init(setup: "Why was the password screen so unpopular?",
              punchline: "Nobody could tell an 8 from a B, and the game knew it."),
        .init(setup: "Why did the mascot get a sequel so quickly?",
              punchline: "Marketing had already printed the cereal."),
        .init(setup: "What did the final boss say to the save point?",
              punchline: "You're new here, aren't you."),
        .init(setup: "Why do old games have such good music?",
              punchline: "When you only get a handful of channels, you have to mean it."),
        .init(setup: "Why did the sprite refuse to be scaled?",
              punchline: "He'd seen what smoothing does to a man."),
        .init(setup: "What's the scariest sound in a coin-op?",
              punchline: "The countdown after you die, when your pocket is empty."),
        .init(setup: "Why does a Mega Drive need two processors?",
              punchline: "One runs the game. The other one holds the music."),
        .init(setup: "What did the Game Gear say to the batteries?",
              punchline: "See you in three hours."),
        .init(setup: "Why was the 32X so lonely?",
              punchline: "It sat on top of everything and belonged to nothing."),
        .init(setup: "How do you make a hedgehog nervous?",
              punchline: "Put a save point in front of him."),
        .init(setup: "Why did the arcade owner smile at the unfair boss?",
              punchline: "He'd just put a deposit on a boat."),
        .init(setup: "Why won't a ninja play cards?",
              punchline: "He keeps throwing the deck."),
        .init(setup: "Why did the platform hero refuse to talk about his feelings?",
              punchline: "He deals with everything by jumping on it."),
        .init(setup: "How does a fighting-game character say goodbye?",
              punchline: "See you at the character select."),
        .init(setup: "What's the most optimistic thing in a beat-'em-up?",
              punchline: "A roast chicken, in a wall, in a city where nothing else works."),
        .init(setup: "Why did the port lose half its frames?",
              punchline: "Six months, one programmer, and a deadline printed on the box."),
        .init(setup: "Why don't sprites ever get lost?",
              punchline: "There's only one direction and somebody already decided it."),
        .init(setup: "What did the cartridge say to the console?",
              punchline: "Blow on me again and I'll work, but we both know that's not why."),
        .init(setup: "Why did the boss have a weak point on its back?",
              punchline: "Because the artist ran out of time on the front."),
        .init(setup: "How do you know a level designer had a bad week?",
              punchline: "Water level."),
        .init(setup: "Why did the healing item taste so good?",
              punchline: "Anything does, after eleven minutes in a wall."),
        .init(setup: "What's a shopkeeper's favourite kind of hero?",
              punchline: "One who can't carry more than six things."),
        .init(setup: "Why did the ghost take the shortcut?",
              punchline: "He'd read the pathfinding."),
        .init(setup: "Why is the second player always the wrong colour?",
              punchline: "Because the palette had four slots and somebody had to lose."),
        .init(setup: "What's the difference between a bug and a feature?",
              punchline: "About two million players agreeing it's fun."),
        .init(setup: "Why did the platformer put spikes under the moving platform?",
              punchline: "To find out who was paying attention. Nobody was."),
        .init(setup: "Why did the racer keep hitting the wall?",
              punchline: "He was told the track had personality."),
        .init(setup: "What did the invincibility star say?",
              punchline: "Ten seconds. Make them count."),
        .init(setup: "Why won't the fighting-game announcer let it go?",
              punchline: "He's said ROUND ONE forty thousand times and he means it every time."),
        .init(setup: "Why did the ninja fail the interview?",
              punchline: "They asked where he saw himself in five years, and he'd only ever seen right."),
        .init(setup: "Why does everyone in the beat-'em-up dress the same?",
              punchline: "Palette swaps. We're all one man having a very long day."),
        .init(setup: "What's the loneliest job in games?",
              punchline: "Second controller port, single-player weekend."),
        .init(setup: "Why did the mascot need sunglasses?",
              punchline: "It was 1992 and it was the law."),
        .init(setup: "Why did the hedgehog fail his driving test?",
              punchline: "Loops."),
        .init(setup: "How do you get a duck out of a platform game?",
              punchline: "You don't. You give him a cape and let him get on with it."),
        .init(setup: "Why did the boss monologue?",
              punchline: "The next room was still loading, and he knew it."),
        .init(setup: "What did the save point say to the hero?",
              punchline: "You've been gone eleven hours. Sit down."),
        .init(setup: "Why did the level have a secret room with nothing in it?",
              punchline: "The something in it got cut on a Thursday."),
        .init(setup: "Why do all these games start in a city at night?",
              punchline: "Fewer background tiles. Same drama."),
        .init(setup: "How does a 16-bit character get its exercise?",
              punchline: "Somebody presses right."),
        .init(setup: "Why did the arcade machine have a mirror above it?",
              punchline: "So the crowd could watch you lose from two angles."),
        .init(setup: "What's the difference between a hero and a boss?",
              punchline: "Health bar placement."),
        .init(setup: "Why did the RPG party carry ninety-nine of everything?",
              punchline: "Because at ninety-nine the number stops going up and so does the fear."),
        .init(setup: "Why do the enemies walk off the edge?",
              punchline: "They've only got one instruction and they follow it beautifully."),
        .init(setup: "Why was the sequel so much bigger?",
              punchline: "Same team, twice the cartridge, and no sleep at all."),
        .init(setup: "How do you spot a rushed ending?",
              punchline: "The sky changes colour and everyone stands very still."),
        .init(setup: "What did the pause menu say?",
              punchline: "Nothing. That was the luxury."),
        .init(setup: "Why did the platform character keep his eyes closed on the jump?",
              punchline: "Two frames. You'd close yours."),
        .init(setup: "Why did the demo mode play itself so well?",
              punchline: "It was recorded by the man who wrote the game, at four in the morning."),
        .init(setup: "What's the most dangerous thing in a side-scroller?",
              punchline: "A staircase."),
        .init(setup: "Why did nobody finish the shoot-'em-up?",
              punchline: "One hit. That's it. That's the review."),
        .init(setup: "Why did the character keep running on the spot?",
              punchline: "The level was still deciding where to be."),
        .init(setup: "What did the port say to the arcade original?",
              punchline: "I've got your levels. I've just misplaced your timing."),
        .init(setup: "Why is the first level always green?",
              punchline: "Grass is cheap and everybody agrees it means start here."),
        .init(setup: "Why did the fighting game add a hidden character?",
              punchline: "So the magazine had something to put on the cover in March."),
        .init(setup: "How many hits does it take to break a barrel?",
              punchline: "One, and a lifetime of wondering why there was a chicken in it."),
        .init(setup: "Why did the sidekick follow you everywhere?",
              punchline: "He's on a leash made of maths and he can't feel it."),
        .init(setup: "What's the sound of a childhood ending?",
              punchline: "A cartridge being pulled out while the console is still on."),
        .init(setup: "Why did the console war end?",
              punchline: "Everyone bought both, eventually, second-hand."),
        .init(setup: "What did the sprite say at the character select?",
              punchline: "Pick me. I've been standing here since 1992."),
        .init(setup: "Why do bosses always have three phases?",
              punchline: "One to learn, one to lose, one to tell people about."),
        .init(setup: "Why did the programmer hide his name in the game?",
              punchline: "The box didn't have room, and he'd been there fourteen months."),
        .init(setup: "What's the polite way to lose a two-player game?",
              punchline: "There isn't one. That's why we played it."),
        .init(setup: "Why did the platform hero collect a hundred of something?",
              punchline: "Because ninety-nine is a number and a hundred is an event."),
        .init(setup: "Why did the enemy respawn the second you turned around?",
              punchline: "Memory. Not spite. Probably not spite."),
        .init(setup: "What did the last continue say?",
              punchline: "Nine. Eight. Seven. Go on then."),
        .init(setup: "Why did the game have an unwinnable state?",
              punchline: "Nobody had invented the word playtesting where that man worked."),
        .init(setup: "Why was the password forty characters long?",
              punchline: "It was carrying your entire life in base sixteen."),
        .init(setup: "What's the difference between a good port and a bad one?",
              punchline: "About four frames, and everybody can feel all four."),
    ]

    // MARK: - Passing remarks

    static let idle: [String] = [
        "Thirty years and I still can't walk past a coin slot.",
        "The trick to a boss is that it always tells you what it's about to do. Once.",
        "I miss instruction manuals. Somebody drew those.",
        "Everything I know about physics I learned from a spring.",
        "There's no pause in an arcade. That was the whole business.",
        "Cartridge games loaded instantly. I'm not saying it was better. I'm saying it loaded instantly.",
        "Somebody in 1991 decided I should run to the right. I've never questioned it.",
        "You had one life, three continues, and a bus to catch.",
        "Every wall in my game is exactly as thick as the artist felt that morning.",
        "I've been standing here so long the desktop has become a level.",
        "Passwords were forty characters long and case sensitive. On a pad.",
        "The music was written by someone with three channels and a deadline.",
        "In my day the difficulty setting was the arcade owner.",
        "Nobody ever explained the plot. There was a printed page and a lot of guessing.",
        "Someone spent a week animating my blink. Nobody has ever mentioned it.",
        "The best games of my era fit in less memory than this speech bubble.",
        "You could tell the good ports because they kept the arcade's timing.",
        "I have never in my life used a save point that felt generous.",
        "There's a whole generation who has never blown into anything to make it work.",
        "The console war was mostly playgrounds arguing about processors nobody had seen.",
        "Somewhere there's a magazine that gave my game 84%. I think about it.",
        "Two players, one screen, no scrolling apart. That was the deal.",
        "Nobody tested my game on a television this big. I can see every pixel of my own face.",
        "There's a man in Japan who decided how fast I walk. I've never met him.",
        "You know what killed the arcade? Us being good enough at home.",
        "I've got four frames of celebration and I've been saving them.",
        "The manual had a map in it. A drawn one. Somebody sat down and drew it.",
        "I was in a magazine cover-mounted demo once. Two minutes of me, and then it stopped.",
        "The rental shop had my box with the sticker over the artwork. That was fame.",
        "Somewhere there's a save file with my name on it and eleven minutes on the clock.",
        "In my game, water is instant death or a slow countdown. There's no third option.",
        "You couldn't pause the arcade. You couldn't pause anything that mattered.",
        "Every ledge I've ever stood on was placed by a person with a grid and an opinion.",
        "The final boss took me three weeks. Nobody was counting but me.",
        "They put the good ending behind everything. Of course they did.",
        "I've never opened a door in my life. I walk to the right and doors happen.",
        "Someone spent a fortnight on the water reflection nobody looks at.",
        "The demo mode was the best marketing there was. Ten seconds of me, on a loop, in a shop.",
        "Loading screens are a thing that happened to other people.",
        "There's a whole language in this: i-frames, hitboxes, cancels. Nobody wrote it down.",
        "My animation is twelve frames. A cartoon gets twenty-four a second. We managed.",
        "You could buy a game because of the box art alone, and often the box art was lying.",
        "Two buttons and a direction. Everything I am fits in that.",
        "The music loops after ninety seconds. I've heard it four hundred thousand times.",
        "The best bit of any game was the bit you found by accident.",
        "I don't have a walk cycle so much as a rhythm I'm stuck in.",
        "Playgrounds settled arguments about processors with absolute confidence and no information.",
        "I've been jumping since before jumping had a name for it.",
        "You can tell when a game was ported by someone who loved it. It's all in the timing.",
        "Half the cheats were things the programmers left in to save themselves walking the level.",
        "Nobody ever beat the last stage on the first credit. That was the design.",
        "The trick with a hard game is that it has to be fair on the second attempt.",
        "The cartridge slot had a bevel so you'd push it in straight. Somebody thought about that.",
        "My sprite is the size of a postage stamp and I'm told people cried at my ending.",
        "There's a version of my game in another country where I'm a different colour.",
        "The credits were a list of first names and nicknames. Everyone was twenty-six.",
        "In 1991 a game was made by seven people. In 1997 it took seventy.",
        "Somebody has spent longer studying my hitbox than I existed for.",
        "You had to know a person who had the magazine that had the code.",
        "The shop demo pod was always broken, and always had a queue.",
        "There's a whole art to dying well. Three frames and a sound, and you're gone.",
        "Sprites don't age. That's not wisdom, that's just how we're stored.",
        "I've never once been asked whether I wanted to fight anybody.",
        "The best games got harder in a way you could feel yourself getting better against.",
        "In an arcade, the crowd behind you was the difficulty setting.",
        "My idle animation exists because somebody thought about what I'd do while you weren't pressing anything.",
        "Games used to end. You'd see the word END and go outside.",
        "Nothing in my world is behind me. There is no behind me.",
        "A password screen was a promise that you'd be back.",
        "I have exactly one facial expression and it has carried me thirty years.",
        "The good levels teach you the trick, then ask for it, then ask for it faster.",
        "You never see the ceiling in my game. There isn't one. Don't look up.",
    ]

    // MARK: - Exchanges

    /// Two-hander conversations. The comedy is in the contrast, and nobody
    /// wins. Character-specific ones only run when both are on screen.
    static let exchanges: [[Line]] = [
        [.init("sonic", "I do the whole level in thirty seconds."),
         .init("knuckles", "Then you've seen none of it."),
         .init("sonic", "I've seen it thirty times.")],

        [.init("ryu", "I travel the world looking for stronger opponents."),
         .init("terry", "I got mine in one city."),
         .init("ryu", "Then you've been lucky with the city.")],

        [.init("toejam", "Do you know where we are?"),
         .init("earl", "No, but the level's random, so neither does anyone."),
         .init("toejam", "That's the most relaxing thing you've ever said.")],

        [.init("axel", "In my game the food is on the floor."),
         .init("blaze", "In a barrel."),
         .init("axel", "In a barrel, on the floor. And it works.")],

        [.init("jim", "I was drawn by hand, frame by frame."),
         .init("sonic", "I was drawn to move fast."),
         .init("jim", "It shows, and I mean that kindly.")],

        [.init("robotnik", "I've built a hundred machines to stop him."),
         .init("sonic", "Ninety-nine."),
         .init("robotnik", "I have one in the shed.")],

        [.init("michelangelo", "Pizza."),
         .init("donatello", "We were mid-conversation."),
         .init("michelangelo", "And now we're talking about pizza.")],

        [.init("leonardo", "The arcade version let four of us play at once."),
         .init("raphael", "The home version let two."),
         .init("leonardo", "That's the console war in one sentence.")],

        [.init("donatello", "Our first arcade cabinet was 1989."),
         .init("ryu", "Mine was 1991 and it ate the world."),
         .init("donatello", "Ours came with a pizza. Metaphorically.")],

        [.init("raphael", "Everyone picks me and then complains about the range."),
         .init("donatello", "I have the range. Nobody picks me."),
         .init("raphael", "That's the trade, and everyone makes it wrong.")],

        [.init("ristar", "I grab things with my arms. They stretch."),
         .init("knuckles", "I punch things. They don't."),
         .init("ristar", "We should team up. You'd hate it.")],

        [.init("moonwalker", "In my game you rescue children by dancing."),
         .init("ryu", "In mine you punch a man through a car."),
         .init("moonwalker", "Different approaches. Same outcome, arguably.")],

        [.init(nil, "Do you ever wonder what's after 1997?"),
         .init(nil, "Every day. Then I remember the arcade shut and I stop."),
         .init(nil, "Fair.")],

        [.init(nil, "Blast processing."),
         .init(nil, "It was a phrase."),
         .init(nil, "It was a very good phrase.")],

        [.init(nil, "How many hits can you take?"),
         .init(nil, "Three, and then I flash for a bit."),
         .init(nil, "Luxury. I flash and then I'm gone.")],

        [.init(nil, "What's your continue screen like?"),
         .init(nil, "Ten seconds and a countdown."),
         .init(nil, "Mine's nine. They knew what they were doing.")],

        [.init(nil, "I've been thinking about the ending."),
         .init(nil, "Ours is a picture of the sky and the word CONGRATULATION."),
         .init(nil, "Singular?"),
         .init(nil, "Singular.")],

        [.init(nil, "Somebody's watching us through a window."),
         .init(nil, "That's a desktop."),
         .init(nil, "That's what I said. A window.")],

        [.init(nil, "In 1993 everything got a blood code."),
         .init(nil, "In 1994 everything got a rating."),
         .init(nil, "In 1995 everything got polygons and we lost the plot.")],

        [.init(nil, "My whole personality is a walk cycle."),
         .init(nil, "Mine's eight frames of standing still."),
         .init(nil, "That's not less. That's restraint.")],

        [.init(nil, "Do you think anyone still has our cartridge?"),
         .init(nil, "In a box. In a loft. Under a coat."),
         .init(nil, "That's immortality, that.")],

        [.init(nil, "The music in your game was better."),
         .init(nil, "The music in every game was better. Three channels and a man with something to prove.")],

        [.init(nil, "I finished mine without a single continue."),
         .init(nil, "Nobody finished yours without a single continue."),
         .init(nil, "Nobody was watching, either.")],

        [.init(nil, "There's a chicken in a wall in my game."),
         .init(nil, "Whole roast?"),
         .init(nil, "Whole roast. Restores everything. Nobody asks.")],

        [.init(nil, "What's your special move?"),
         .init(nil, "I press two buttons and hope."),
         .init(nil, "That's everyone's special move.")],

        [.init(nil, "They say the arcades are gone."),
         .init(nil, "They say a lot of things."),
         .init(nil, "They said blast processing.")],

        [.init("axel", "You're me in two years."),
         .init("axel3", "I'm you with better legs and a worse story."),
         .init("axel", "The story was fine. A man took our city.")],

        [.init("sonic", "There's a version of me in a pinball machine."),
         .init("spinball", "There's a version of you in everything by now."),
         .init("sonic", "That's the job.")],

        [.init("sonic", "You're me, rendered."),
         .init("sonic3d", "I'm you with a shadow that's its own sprite."),
         .init("sonic", "Must be nice, having a shadow.")],

        [.init(nil, "Did you ever get an add-on?"),
         .init(nil, "A CD drive, and then a thing on top of that."),
         .init(nil, "How many holes does one console need?")],

        [.init(nil, "My game had a password."),
         .init(nil, "Mine had a battery."),
         .init(nil, "Mine had neither, and it knew what it was doing to us.")],

        [.init(nil, "Somebody wrote our music on a chip with six channels."),
         .init(nil, "Somebody wrote their own tools to do it."),
         .init(nil, "And it still gets stuck in people's heads. That's the part I like.")],

        [.init(nil, "Would you have wanted three dimensions?"),
         .init(nil, "I've seen what happened to the ones who got them."),
         .init(nil, "Fair.")],

        [.init(nil, "How much of you is on the cartridge?"),
         .init(nil, "Every frame I have. There's no loading, so there's no hiding."),
         .init(nil, "That's why we look like this and move like that.")],

        [.init("terry", "Are you okay?"),
         .init("ryu", "That's not a question, that's your special."),
         .init("terry", "It's both. That's what makes it good.")],

        [.init("knuckles", "You can fly, he can run, and I climb walls."),
         .init("tails", "You also glide."),
         .init("knuckles", "I glide *down*. Let's be honest about what that is.")],

        [.init("robotnik", "I have built a hundred machines."),
         .init("mecha", "I am one of them."),
         .init("robotnik", "You are the good one. Don't tell the others.")],

        [.init("michelangelo", "Four players, one cabinet, one pizza."),
         .init("raphael", "You ate most of it."),
         .init("michelangelo", "I was player one. There are responsibilities.")],

        [.init("donatello", "I did the maths on the reach."),
         .init("leonardo", "And?"),
         .init("donatello", "I have the best weapon and the worst reputation.")],

        [.init("jim", "I was a worm before I found the suit."),
         .init("sparkster", "I'm an opossum in armour."),
         .init("jim", "Nobody in this line of work is what they look like.")],

        [.init("toejam", "We're aliens. Nobody ever asks about that."),
         .init("earl", "They ask about the shorts."),
         .init("toejam", "They always ask about the shorts.")],

        [.init("donald", "I was in a game about illusions."),
         .init("moonwalker", "I was in one about dancing at people until they fell over."),
         .init("donald", "Neither of us should have worked and both of us did.")],

        [.init("ryu", "There's always a stronger opponent."),
         .init("robert", "There's always a richer one, too."),
         .init("ryu", "That's not the same ladder.")],

        [.init("musashi", "I had a horse stage and a surfboard stage."),
         .init("gambit", "I had a staff and a coat that never moved right."),
         .init("musashi", "The coat is the hard part. Cloth is always the hard part.")],

        [.init("sketch", "I was drawn into my own comic by the villain."),
         .init("jim", "I was drawn by people who used to do Saturday cartoons."),
         .init("sketch", "Then you got the better deal and I got the better story.")],

        [.init("axel", "Three of us against a city."),
         .init("blaze", "Two of us, mostly. Adam got kidnapped."),
         .init("adam", "I can hear you.")],

        [.init("sonic", "I was on the box of a console."),
         .init("ristar", "I came out the same year they stopped making them."),
         .init("sonic", "Timing. It's the only thing I've ever been good at.")],

        [.init("skate", "I'm the fast one."),
         .init("spinball", "You're the fast one in a game where I'm a ball."),
         .init("skate", "A ball isn't fast. A ball is *dropped*.")],

        [.init("max", "I move slowly because I only need to arrive once."),
         .init("earl", "That's the first sensible thing anyone's said here."),
         .init("max", "I say one thing a week.")],

        [.init("galsia", "I'm the first enemy in the first street."),
         .init("slum", "I'm the third game's version of you."),
         .init("galsia", "Do they still walk into your knife?"),
         .init("slum", "Every time.")],

        [.init("axel1", "1991."),
         .init("axel", "1992."),
         .init("axel3", "1994."),
         .init("axel1", "Somebody's going to have to explain the trousers.")],

        [.init(nil, "What's the worst level in your game?"),
         .init(nil, "Water. Obviously water."),
         .init(nil, "Everybody says water and everybody is right.")],

        [.init(nil, "Do you remember your first frame?"),
         .init(nil, "Standing, facing right, waiting."),
         .init(nil, "Same. We all start facing right.")],

        [.init(nil, "Somebody paused us for eleven hours once."),
         .init(nil, "I stood there the whole time."),
         .init(nil, "So did I, and my arm was up.")],

        [.init(nil, "Have you ever been in a magazine?"),
         .init(nil, "Two pages and a score out of a hundred."),
         .init(nil, "What did you get?"),
         .init(nil, "Enough that my mother kept it.")],

        [.init(nil, "How many enemies are in your game?"),
         .init(nil, "About nine, in different colours."),
         .init(nil, "That's the trick, isn't it. Nine and a palette.")],

        [.init(nil, "Do you get a health bar?"),
         .init(nil, "I get three hits and a flashing sprite."),
         .init(nil, "Luxury. I get rings, and I drop them everywhere at the worst possible moment.")],

        [.init(nil, "Somebody rented us for a weekend and finished us in one night."),
         .init(nil, "That's not a failure. That's a very good weekend.")],

        [.init(nil, "The cheat code was in a magazine."),
         .init(nil, "The magazine was in a shop."),
         .init(nil, "And the shop was thirty minutes away by bus. That's what it cost to know things.")],

        [.init(nil, "What did they cut from your game?"),
         .init(nil, "A whole zone. It's in the code, you can still hear the music."),
         .init(nil, "That's a lovely way to be haunted.")],

        [.init(nil, "I've been thinking about the second controller."),
         .init(nil, "Don't."),
         .init(nil, "Somebody sat there. For years, somebody sat there.")],

        [.init(nil, "My game had a difficulty select."),
         .init(nil, "Mine had a man in an arcade watching the till."),
         .init(nil, "Yours was more honest.")],

        [.init(nil, "Do you think we were rushed?"),
         .init(nil, "Everything was rushed. Christmas doesn't move."),
         .init(nil, "That's the whole industry in one sentence.")],

        [.init(nil, "What happens to us if nobody plays?"),
         .init(nil, "We loop. We've always looped."),
         .init(nil, "That's not so bad, put like that.")],

        [.init(nil, "Somebody's built a machine that plays my game perfectly."),
         .init(nil, "Frame by frame?"),
         .init(nil, "Frame by frame. It's beautiful and I hate it.")],

        [.init(nil, "Best sound in your game?"),
         .init(nil, "The one when you pick something up."),
         .init(nil, "Every time. That little rising note. That's the whole business.")],

        [.init(nil, "Were you ever on a demo disc?"),
         .init(nil, "Cover-mounted. Two minutes and a screen telling you to buy me."),
         .init(nil, "Two minutes is a career, some years.")],

        [.init(nil, "I keep thinking about the man who drew the box."),
         .init(nil, "Airbrush. Always airbrush."),
         .init(nil, "And nothing inside looked like it, and nobody minded.")],

        [.init(nil, "What's your ending?"),
         .init(nil, "The sky turns orange and my sprite waves."),
         .init(nil, "Mine's a list of names. I like mine.")],

        [.init(nil, "Do you ever wonder who we were for?"),
         .init(nil, "A kid, a rented television, and a bus timetable."),
         .init(nil, "That's a good answer. I'm having that.")],

        [.init(nil, "They say the graphics have aged."),
         .init(nil, "Nothing's aged. Everything is exactly where it was left."),
         .init(nil, "That's the point of pixels.")],

        [.init(nil, "How long is your game, really?"),
         .init(nil, "Forty minutes, if you're perfect."),
         .init(nil, "And six weeks if you're eleven.")],

        [.init(nil, "Do you know what a hitbox is?"),
         .init(nil, "It's the part of me that's actually me."),
         .init(nil, "It's smaller than you'd think, and it's off to the left.")],

        [.init(nil, "Someone asked me what my game was about."),
         .init(nil, "And?"),
         .init(nil, "A man goes right, and things try to stop him. They cried, apparently.")],

        [.init(nil, "Two-player was the whole medium for a while."),
         .init(nil, "One sofa. One screen. No scrolling apart."),
         .init(nil, "You had to like the other person or learn to.")],

        [.init(nil, "What did your box promise?"),
         .init(nil, "Arcade-perfect conversion."),
         .init(nil, "And was it?"),
         .init(nil, "It was arcade-adjacent.")],

        [.init(nil, "Somebody's put us on the internet."),
         .init(nil, "What's the internet?"),
         .init(nil, "Something with a modem, apparently. Ask again in a few years.")],

        [.init(nil, "I've got a level that plays underwater and one that plays in a casino."),
         .init(nil, "Everyone has the casino."),
         .init(nil, "Everyone has the casino, and nobody has ever asked why.")],
    ]

    /// Lines only one character would say. Everyone else draws on `idle`.
    static let personal: [String: [String]] = [
        "sonic": ["I was nearly called Mr Needlemouse. Think about that.",
                  "They shipped my sequel on a Tuesday and named the day after me.",
                  "Rings are just health you can drop everywhere at the worst possible moment.",
                  "I have one speed and a great deal of momentum. It's not the same as control.",
                  "Somebody put a casino inside a hill. Nobody has ever explained that to me."],
        "knuckles": ["I glide, I climb, I punch. Nobody's ever needed a fourth thing.",
                     "I was in a game with my name on it and I still got tricked.",
                     "Guarding an island is a job. It is not an adventure. I've made peace with it.",
                     "My whole character is being lied to once and never getting over it."],
        "tails": ["I can fly. Not far, and not for long, but I can fly.",
                  "Two tails. Everyone asks. Yes, they work.",
                  "Player two, in a game where player one never waits.",
                  "I fixed the plane. Nobody in the cutscene says thank you."],
        "robotnik": ["Every machine I build is defeated by a hedgehog. Every single one.",
                     "I have a doctorate. Nobody uses it.",
                     "The trick is to put the weak point where he can obviously reach it. It's called *design*.",
                     "Six eggs, six machines, six defeats, and I have never once considered stopping."],
        "mecha": ["I am what happens when the doctor gets it nearly right.",
                  "Silver, spiked, and built to look like the thing he can't catch.",
                  "I don't need rings. I don't need air. I do need a floor, which was the oversight."],
        "ristar": ["My arms reach further than you'd think. That's the whole game.",
                   "I came out the same year as some very loud consoles. Nobody noticed me.",
                   "I grab things and headbutt them. It reads better than it sounds.",
                   "Everybody who played me remembers me. There were about eleven of them."],
        "terry": ["Are you okay? Buster wolf.",
                  "My hat has been through more than most people.",
                  "I fight in a city called South Town, which tells you everything about the writing.",
                  "The jacket, the hat, the jeans. I've never changed and nobody's asked me to."],
        "ryu": ["The answer is always more training.",
                "I fought a man who could throw fire. So can I. We had a lot to discuss.",
                "I have no home, no job and one very good friend. It's a life.",
                "Six buttons. Everything I am fits in six buttons."],
        "robert": ["Money never got me a single win in this thing.",
                   "I'm the friend of the main character, which is its own career.",
                   "Italian shoes, Japanese school, American arcade. Nobody thought about it too hard."],
        "musashi": ["A ninja in 1993 got a horse level and a surf level. I earned both.",
                    "I throw shuriken in eight directions and I have never once missed by design.",
                    "The soundtrack is better than the ninja. I've made my peace with that."],
        "jim": ["Groovy.",
                "I'm a worm in a suit. The suit does the walking.",
                "They animated me by hand. That's why I move like a cartoon and land like a sack.",
                "My gun is a real gun and my head is a whip. Nobody stopped the artist."],
        "toejam": ["We crash-landed. We were fine. We're always fine.",
                   "Nine pieces of ship, one planet, no hurry.",
                   "There's a man with a lawnmower on level six and he still visits me."],
        "earl": ["I do not run. I have never run. Running is for people who left late.",
                 "There's a hot tub in this game and I have found it every time.",
                 "I am shaped like this on purpose. Somebody drew me and thought: yes."],
        "donald": ["I was in a game about illusions. Half of it wasn't there.",
                   "The cape turns things into other things. Don't ask me how, ask the mouse.",
                   "I have three nephews and a temper and only one of those is in the game."],
        "moonwalker": ["The dance was the attack. That's not a metaphor, it's the mechanic.",
                       "My songs are on the sound chip. Six channels and Smooth Criminal.",
                       "You rescue children by dancing. In 1990 nobody blinked."],
        "sparkster": ["Opossum. Not a squirrel. It's on the box.",
                      "Rocket pack, sword, and a wall to bounce off. That's the loop.",
                      "Konami gave me everything except a sequel anybody could find."],
        "pulseman": ["The studio that made me went on to make something with monsters in it.",
                     "I'm half electricity. It's less useful than it sounds and more fun.",
                     "I was a Sega Channel game. You had to *subscribe* to me."],
        "gambit": ["The card does the work. I just have to look like I meant it.",
                   "I have a staff, a coat and an accent, in that order of usefulness.",
                   "Clone Wars had six playable mutants and one very long password."],
        "sketch": ["I was drawn into my own comic. The artist was not kind.",
                   "I punch through the page. It costs me health to do it, which is the joke.",
                   "There's a rat in my pocket who is better at this than I am."],
        "axel": ["Grand Upper. Say it properly.",
                 "Two of us walked into a city with nothing and it worked out.",
                 "There's a roast chicken in that wall and I intend to eat it."],
        "blaze": ["Everyone remembers the kick. Nobody remembers the projectile.",
                  "I left the police to do this. The police were the problem.",
                  "Somebody drew me a new outfit for every game and I never got a vote."],
        "max": ["I am slow because I only need to arrive once.",
                "Wrestler. Not a boxer, not a brawler. Wrestler.",
                "I pick people up and the game says: yes, that's allowed."],
        "skate": ["I'm the fast one. Ask anyone who isn't a hedgehog.",
                  "Rollerblades in a street fight. I was nine and it was fine.",
                  "My brother's the one people know. I'm the one people pick."],
        "adam": ["I was in the first one and then I was a hostage. Ask my agent.",
                 "Boxing. Not martial arts, not wrestling. Boxing.",
                 "The police car special was mine before it was anybody's."],
        "axel1": ["1991. Three of us, one city, and a police car that solved everything.",
                  "We had a special move that called in an air strike. Nobody questioned it.",
                  "I'm the first draft of a man everybody thinks they remember."],
        "blaze1": ["The first game gave me a car-sized special and no explanation.",
                   "Everybody remembers the sequel. I was there first.",
                   "Red dress, city on fire, and one very good jump kick."],
        "axel3": ["Two years on and they gave me longer legs and a worse ending.",
                  "Bare Knuckle III at home. They renamed it and made it harder for you.",
                  "Same city, third time. Somebody should look into the policing."],
        "spinball": ["I'm the one in the pinball table. Somebody had to be.",
                     "Different studio, different country, different face. Same hedgehog.",
                     "In my game you don't run. You get *fired*."],
        "sonic3d": ["Pre-rendered. My shadow is a separate sprite and it follows me everywhere.",
                    "Isometric. It means you walk diagonally and blame the controller.",
                    "1996, and they were still finding new ways to make a hedgehog."],
        "galsia": ["I'm the first thing you hit in the first street. Somebody has to be.",
                   "I come at you with a knife and a hopeful expression.",
                   "I've been beaten up in three games and I keep turning up. That's commitment."],
        "donovan": ["Two of us come at once. That's the whole plan.",
                    "I'm the one people mistake for the boss.",
                    "No shirt, all confidence. It's carried me this far."],
        "eagle": ["Kick first. There isn't a second part.",
                  "Trousers, boxing boots and no shirt. It was 1992.",
                  "I'm named after a bird and I fight like a man falling downstairs."],
        "slum": ["I turn up in the third game with a bigger hat and worse manners.",
                 "Third game, same street, new palette. That's the career.",
                 "I've got a bat and a grudge and no lines."],
        "raphael": ["Two sai and a temper. That's the build.",
                    "I'm the one everybody picks, and then complains about the range.",
                    "Cool but rude. It's on the toy box and I've never argued with it."],
        "leonardo": ["Leader. It's not a personality, it's a rota.",
                     "Four of us on one cabinet. Somebody always took the last continue.",
                     "Two katana and the least interesting opinions. I'm at peace with it."],
        "michelangelo": ["Nunchaku, in the American release. In some countries they gave me a grappling hook.",
                         "Pizza. That's it, that's the line.",
                         "Party dude is a job title and I have never once been off duty."],
        "donatello": ["The bo has the longest reach in the game. Nobody uses it.",
                      "I did the machines. Somebody had to.",
                      "Slowest swing, longest reach. It's the most honest trade in the game."],
    ]

    // MARK: - Picking

    /// Exchanges both of these two can actually hold: every named line has to
    /// belong to one of them, or half the conversation goes missing.
    static func exchanges(for pair: (String, String)) -> [[Line]] {
        exchanges.filter { lines in
            let named = Set(lines.compactMap(\.who))
            return named.isEmpty || named.isSubset(of: [pair.0, pair.1])
        }
    }

    /// What this character says when it has nothing in particular to say.
    static func smallTalk(for id: String) -> [String] {
        (personal[id] ?? []) + idle
    }
}
